# Generated by Django 4.1.5 on 2023-01-08 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('prenomm', models.CharField(max_length=200)),
                ('date_naissance', models.DateTimeField()),
                ('lieu_naissance', models.CharField(max_length=200)),
                ('nationalite', models.CharField(max_length=200)),
                ('filiere', models.CharField(choices=[('GESTION', 'Gestion'), ('STAPS', 'Staps'), ('MAS', 'Mas')], max_length=200)),
                ('Specialite', models.CharField(choices=[('EPS', 'Eps'), ('Management du Sport', 'Mds'), ('EVENEMENTIEL', 'Eve'), ("Metier du sport et de l'evenement sportif", 'Mso')], max_length=200)),
                ('niveau', models.CharField(choices=[('1', 'Niveau1'), ('2', 'Niveau2'), ('3', 'Niveau3')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natureEvaluation', models.CharField(choices=[('Contrôle_Continue', 'Cc'), ('Session_Normale', 'Sn')], max_length=50)),
                ('note', models.FloatField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_semestre', models.IntegerField()),
                ('date_debut', models.DateTimeField(null=True)),
                ('date_fin', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniteEnseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_UE', models.CharField(max_length=20)),
                ('intitule_UE', models.CharField(max_length=500)),
                ('volume_Horaire', models.IntegerField()),
                ('nombre_credit', models.IntegerField()),
                ('coefficient', models.IntegerField()),
                ('groupe', models.CharField(choices=[('Fondanmental', 'Fondamentale'), ('Transversal', 'Transversale'), ('Professionel', 'Professionnele')], max_length=200)),
                ('etudiant', models.ManyToManyField(through='bulletin.Evaluation', to='bulletin.etudiant')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletin.semestre')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='uniteEnseignement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin.uniteenseignement'),
        ),
    ]
