# Generated by Django 4.1.5 on 2023-01-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0003_rename_prenomm_etudiant_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(choices=[('FEMININ', 'Feminin'), ('MASCULIN', 'Masculin')], default='MASCULIN', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='semestre',
            name='date_debut',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='date_fin',
            field=models.DateField(null=True),
        ),
    ]
