# Generated by Django 4.1.5 on 2023-01-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0007_rename_dateevaluation_evaluation_date_examen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='date_CC',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='semestre',
            name='date_SN',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='date_Examen',
            field=models.DateField(null=True),
        ),
    ]
