# Generated by Django 4.1.5 on 2023-02-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0009_uniteenseignement_specialite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='Specialite',
            field=models.CharField(choices=[('EPS', 'Eps'), ('Management du Sport', 'Mds'), ('EVENEMENTIEL', 'Eve'), ('MSO', 'Mso'), ('Tronc Commun', 'Trc')], max_length=200),
        ),
    ]
