# Generated by Django 4.1.5 on 2023-02-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0010_alter_etudiant_specialite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='Specialite',
            field=models.CharField(choices=[('EPS', 'Eps'), ('Management du Sport', 'Mds'), ('EVENEMENTIEL', 'Eve'), ('MSO', 'Mso')], max_length=200),
        ),
        migrations.AlterField(
            model_name='uniteenseignement',
            name='Specialite',
            field=models.CharField(choices=[('EPS', 'Eps'), ('Management du Sport', 'Mds'), ('EVENEMENTIEL', 'Eve'), ('MSO', 'Mso'), ('Tronc-Commun', 'Trc')], max_length=200, null=True),
        ),
    ]
