# Generated by Django 4.1.5 on 2023-02-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0012_alter_uniteenseignement_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniteenseignement',
            name='Specialite',
            field=models.CharField(choices=[('Management du Sport', 'Mds'), ('EVENEMENTIEL', 'Eve'), ('MSO', 'Mso'), ('Tronc-Commun', 'Trc'), ('EPS', 'Eps')], max_length=200, null=True),
        ),
    ]
