# Generated by Django 4.1.5 on 2024-01-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0019_alter_etudiant_crs1_alter_etudiant_crs2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(max_length=50)),
                ('debut_SN1', models.DateField(blank=True, default='', null=True)),
                ('fin_SN1', models.DateField(blank=True, default='', null=True)),
                ('debut_SN2', models.DateField(blank=True, default='', null=True)),
                ('fin_SN2', models.DateField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='redoublant',
            field=models.CharField(choices=[('1', 'Oui'), ('0', 'Non')], default='non', max_length=10),
        ),
    ]
