# Generated by Django 4.1.5 on 2024-01-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0020_calendrier_etudiant_redoublant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='redoublant',
            field=models.CharField(choices=[('1', 'Oui'), ('0', 'Non')], default=0, max_length=10),
        ),
    ]
