# Generated by Django 4.1.5 on 2024-01-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0021_alter_etudiant_redoublant'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='date_RT',
            field=models.DateField(null=True),
        ),
    ]
