# Generated by Django 4.1.5 on 2024-02-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0022_semestre_date_rt'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='annee_acadmeqique',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
