# Generated by Django 4.1.5 on 2024-02-01 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0023_semestre_annee_acadmeqique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semestre',
            old_name='annee_acadmeqique',
            new_name='annee_academique',
        ),
    ]
